apiVersion: v1
kind: Service
metadata:
  name: hosty-service
spec:
  selector:
    app: hosty
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-server-config
data:
  RANDOM_BACKGROUND_COLOR: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosty-deployment
  labels:
    app: hosty-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hosty
  template:
    metadata:
      labels:
        app: hosty     
    spec:
      containers:
      - name: hosty-container
        image: thomasdom/hosty:2.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: web-server-config
